### ISSUE TITLE
Issue in Physics 

### ISSUE THREAD

**Issue by Shubhaankar-Sharma** [aman-atg/asteroids-game#1]
when the space fighter has a certain velocity the bullet needs to eject at a relative velocity that you have set but the speed of the bullet is always greater as the speed of bullet would be Vrelative + Vrocket.............and the spaceship is not conserving momentum...........but overall the app is very good

**Comment by aman-atg** [comment]
Thanks for mentioning both the issues.. You are welcome to work on them If you feel like it. I'll be happy to Merge Your PR.
