### ISSUE TITLE
Add lives

### ISSUE THREAD

**Issue by ahmkha-cmd** [aman-atg/asteroids-game#2]
Hello, I have a suggestion that I would like to tell you. Can you add more lives (Ex. 5)? It might make the game more fun.

**Comment by aman-atg** [comment]
@ahmkha-cmd great suggestion! Would you like to make a PR for this change? If not then I'll update it myself.

**Comment by ahmkha-cmd** [comment]
I will try to make a PR and change the code for the game and I will let you know of the progress here.

**Comment by ahmkha-cmd** [comment]
I edited the const.js file line #2 and changed the game lives to 5 but did not get to test it. The repo I edited the code in: https://github.com/ahmkha-cmd/asteroids-game

**Comment by aman-atg** [comment]
Sorry @ahmkha-cmd, took me a long time to respond due the work and everything.. 
I see that you have done the changes.. now you just to create a PR to this Repository. 
Refer to these links if you aren't familiar with the flow
 - [link 1](https://opensource.com/article/19/7/create-pull-request-github)
 - [link 2](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by ahmkha-cmd** [comment]
@aman-atg I created a pull request for this repository.

**Comment by aman-atg** [comment]
@ahmkha-cmd, merged the pr.. closing this issue. Thanks for contributing.
